CXX = g++
CPPFLAGS = -I/remote/pi213c/casas/EFTCAMB/cosmomathica-tests/cosmomathica/ext/copter-0.8.7/include
CXXFLAGS = -g -O2 -fopenmp
LDFLAGS = -L/remote/pi213c/casas/EFTCAMB/cosmomathica-tests/cosmomathica/ext/copter-0.8.7/lib -lcopter


all: distance fwt kaiser integration linear rpt2 spt2 tmp_sig

clean:
	@rm -f distance fwt kaiser integration linear rpt2 spt2 tmp_sig
